apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: mq-mvp
  owner: mq-mvp
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/mq-mvp/multi-tenancy-gitops-apps.git
