apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgA3dEbUd7hn/heMaFXOh5QpSu2e50NFQeQ7a4WAvf1ntiu7VIW7fEVYuQEcVFaubhHnWn7jG7v2mvVNueZ/GC1felCg3eGz8pc8DcmfkYVSRwcW2nAeudIdstnT/LZYBBg7FNMbKq+gbysKzYQB+Wgw8NYy5SqsqOvtmZu/BxnUMWsOtbMYRzqtcrJXhwfD2P2iSnO+wFGd+a64zAG+92B6WW0yjJr3cm1rPpbyFXtKIJ1yTS7Ve1v9joYzY7DmPkqF9vebOvvzncQQ59oRIhRoGPenkQyvnmBRhKSygHF6p4MqtWxce9wsMEIKQHFCL0d4LdpKWwLeAuKlrRX9Mm/h5Gem8XaLgo1NChMHDgHTnH/T3ErqAfhz0tQwGLxYlDsl/aPpq9jVEiMT8RevTvZvfjBMViZ0T/DkwQiI3azYiZprcbVMEhQLwb9CDEMORiDisjFP16CS8HU1WpGPZTkzygw3cGCxcWE0ledb0V/zYxPsWX+ZR2uDVpTdoQM8+mKxN4+FokT7NfKpq/htpkPFWlb+a3Hh2RSDzAHf340TCeW4Ta9gGecUh1AHi+VdtzFj3/2JPu/Muccz5JplISuWCqZrwoTX6TN3wR6zsM00zSmHCw0xAYvU8PfHIls/x71GaHh4gJ5LTNLikEjY+u72ULBh4Jlv+6Ap7Ve5lEshY3xBJLCMKimTXWvF0U5JO4/a6POXLPXGTYthSvzY587qczLfZlxA+A34GT6oCwOtOCJbcRDxBV3L
    username: AgBTW2N+2SPPLgWzq5Xcj5jEp/02unQinN+xpBMF6xZu6bmv9jbnf61RwwSe8LRc5dOVR9z+j8fej6paZ/nglDqz9LUr1zMF+jQN1zDm3KmTYudX2vuVR20x/ahosFRuhz5vQMsdH/CBV0XL0RXnH2sc+RhxU8snI7T+Vq6Z36hzAvujEbp/UyKgfZWRpqgAB63GBppA+F5coDxV9FQv5dL+JYuINdOXVb96tzoWu9wm4W+l4TmrPlzEbcTDSR106dfwxMjK8JUPTFQ6F5O2lIHtmhSuEQXjx+vBL1ECUCrbqnzdx49glfCq7N3g3jKxlqlZYQRswt4COZruIIaP98VseJX36gCoMvR+7rDwYUjm6MuyEvYF3jL2sXD2PTrlFWkNBf8TfRbpJlQKCGxsn6g3cAv3uYWzqK0tA8RytozZvUrvOkz6Klg0OKYHumf1lU+mgmMdzpjdyEQVBQGQnYW8lTZqYMaOV4Gweon2YDNhmVikDBsyDOu4x0PeT3/ss/h/6pp4qJml1plpnM4jowI+NL17tsLLEcm5ThRCujiCK8JQMidWs6eldPdiSWO/1a1IGPmQ7W1YyzOOhjwSJNE4HienJKYPZH2n4/yRNzqffdw16bxgT4+82UxIKiXt921LVyuN2dROx6+D0k6ke2bvPWalQDd969un4Ms5bIrE9qJKZCOZLP4bhYXjgghB306LMImbKp4=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

