apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgArpEbq930sbACR4SmLoorwXK3KyKGAZ0OeEhsKEQdoNSC8DTc7gyVpscNhweLxZTdAkRkH/AcNLdn3b1O8lN3O+aSHh51zbs2ZPhee+4BRw82mQ13Ga/DofDX8ORyojAf6p4L9WyS30igXsLUCsuzen39OF7CHdyeUU/yIxX/K0s8BSwgdbOeJRfIossWJT6FkLVZYJba9gxbuIaNDr5RPiE9TBVnqXRbkmIy3OYXCfJnxuY5QaxHDW1dIkawgpx70u2ROyx+8PuedoRF91JiLu3AwoirpetBL/aIvOetgNRDz7PbFGpYWmEBCyPC1Y1hH8Py+Abjs1CTJgM8vo7gLlVsr10QBGVDyTL+sSGfTFo5IQBjViWsIK3W9+Fe3tus5WacaiWTEHjmGDnsw7EjIwckdD1otbcJdbbOO5XMlpxljrY/zmNTx6USe4/eIFx7jbJaQcjrmjWzbZS32B5waElAQIVNFNx9KSMkYnQFobnvpwb/oeDXMOimcmj4PN/A1iWKdIXV2ov2Q/90jYnKjWLc5UqJ9STt/ID6vnTGzEvYS2bbZkP0RMLKVONXRLMi+OnJSg3Q1O+Aptaqx9aEA82FvNhizoutM8WgTOyR6M5zupyV+NPHz3udnSP2vB8I+9qFN4RG8ljDOagSAJXNwQk0DSDJQhAhigHyq10T0Xgf2AVR1b92cwY596bIoeLnY6RuehR6NH7jcx1GxhOW6UxQVQuTSaOLJJnXbF5t7tokrMuR+kDuN5EsLN0NDvBDg4Yeibblv4OWiwe/9F4gx5/AUyMwlPaBmCWq2SwZ8IEmCBxVURbz3Q5yra0AeRXSVGnKcIDfH6kbBRMma1LorDRkPat4TsnmoUR+qsVPnjA6hSTzqqOPU6eM/V0IOb4yjvCLUpe6GV27/ihZeInFuZEKv8O+mlosPHyTRwoGdLQ==
    IBM_ENTITLED_REGISTRY_USER: AgAbx9IgiHMlobWGai4U2n6IeHtpSQNeFPpCYplAWVg3Ztd/6tBmIo7M/kgAXB1SuAeWbAZNBT69EkusIsQUyiVjtaHMvKFuz8VXHfnLffYGImZJ6TzuuXLBvnJiYwTGZ+QbZEtAnkBdCIUxJxR7//jKfYWVIg18mVPBMMSuShrtOIH3ky/XFODEOvw7XTFkLKzgw7auyok1WLgUd4/4tBZ6yDTZZw61Da5SwFhF4luVHQArRSR9DD+VJS6Tfz8gxVGCGKYMROhWVpp6i81XY9LMFAc3bzoQHyPDfTgAx2Vel9AY+aEvjQJHrnaB4b4RJEP++K+Z3rqo3QrOLCRvUx0kVw2TEA0w5mLwmcqk6d/YYfelu5ODcwEiO3s5jEJMpYNF7y+x1BLmkTBO82e2OhmGGEdF+032f2JJ3PAZiJyRpbEiLQF6AR8pugg5F075DVtNzp1IwdFdxPhtcryd6X6TcjjNBKELXwjNPPUVz6CyiV079E9pWmm+P7MBiQSOMruRzC/BYhT2ojBuiSHEFLVGNu5iwo1vgmP00qkQM+i+pBjSugsOnzrHg+MRUapVvSaL/JXq0cqlaszdxtxqi+/ecmHvprr2VuXEjZwHI6cUf0Li2fhjeuh+pTsL3LcQt9/C08t8LhVqf+XSNXmzTtKFWMhGwdQ6KTzMz8fbdbVfO7qXl4Ir9PqrfCQlvEgDl108tQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

